### ISSUE TITLE
BackOffice: Módulo de Informaciones

### ISSUE THREAD

**Issue by jjgumucio** [RancaguaInnova/back-office#42]

**Comment by JEPEREZR** [comment]
- Se agregador CRUD para colección de  categorías de información
- Se han realizado modificaciones al CRUD de departamentos, agregando nuevos campos necesarios para el correcto funcionamiento del webview.

**Comment by JEPEREZR** [comment]
Se agrega  coleccion de departamentos para modulo de informaciones y se modifica el departamento actual a departamentos municipales
